// flow-typed signature: ce4ccf3e6e405b1717c7ab6a8d8cfa2d
// flow-typed version: <<STUB>>/babel-preset-signalsciences_v^0.0.1/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-signalsciences'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-signalsciences' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-signalsciences/index' {
  declare module.exports: $Exports<'babel-preset-signalsciences'>;
}
declare module 'babel-preset-signalsciences/index.js' {
  declare module.exports: $Exports<'babel-preset-signalsciences'>;
}
