// flow-typed signature: 8f0877866fcd302a43bde71fccde5a86
// flow-typed version: <<STUB>>/eslint-config-signalsciences_v^0.0.1/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-signalsciences'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-signalsciences' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-signalsciences/index' {
  declare module.exports: $Exports<'eslint-config-signalsciences'>;
}
declare module 'eslint-config-signalsciences/index.js' {
  declare module.exports: $Exports<'eslint-config-signalsciences'>;
}
