// flow-typed signature: bb9eeca9c4824c476fd518fb5429b135
// flow-typed version: <<STUB>>/jest-preset-signalsciences_v^0.0.2/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-preset-signalsciences'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-preset-signalsciences' {
  declare module.exports: any;
}
