// flow-typed signature: 7e6d178de51b7bfc0ac0e1a461cb5bc5
// flow-typed version: <<STUB>>/rollup-config-signalsciences_v^0.0.1/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-config-signalsciences'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-config-signalsciences' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-config-signalsciences/index' {
  declare module.exports: $Exports<'rollup-config-signalsciences'>;
}
declare module 'rollup-config-signalsciences/index.js' {
  declare module.exports: $Exports<'rollup-config-signalsciences'>;
}
